# .pre-commit-config.yaml
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.7
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
          - id: ruff-format
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: [--profile=black, --filter-files]
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.7
      hooks:
        - id: bandit
          args: ["-x", "./venv"]

# Optional: create a pyproject.toml for tool configuration
